### PR TITLE
Updating threat model with new section on TKey Unlocked

### PR DESCRIPTION
**Pull request by mchack-work**

### CODE REVIEW

**Comment by secworks** [comment]
Nits on row 179: “as desribed” --> “as described”

**Comment by dehanj** [comment]
I have added the latest release.

> Nits on row 179: “as desribed” --> “as described”

Fixed.

**Comment by dehanj** [comment]
@secworks @kfreds adding you as reviewers so you get the notification about changes.

**Review by secworks — APPROVED** [review]
Looks good!

**Pull request merged**
