### PR TITLE
Add software reset example for the mta1 programmer

### PR DESCRIPTION
**Pull request by cibomahto**
This adds a test script demonstrating how to use the programmer board to issue a hardware reset on a connected mta1-usb-v1 device.

### CODE REVIEW

**Comment by quite** [comment]
I'm trying this out now. After installing the apparently required pkgs i get `AttributeError: 'ice40_flasher' object has no attribute 'dev'`. Something not comitted?

I think i'll add a `requirements.txt` so that this can be easily run using virtualenv and `pip install -r requirements.txt`  in the same.

**Comment by cibomahto** [comment]
Sounds good for requirements.txt- I need to (separately) circle back on making the production test environment reproducible as well.

The 'dev' attribute error is misleading, what it means is that the Python HID library couldn't find or connect to a programmer. dev is created here:
https://github.com/tillitis/tillitis-key1/blob/3f56a243cc22afda6ff3856ad585c93f357770c2/hw/boards/mta1-usb-v1/test/hid_test.py#L13

Was the programmer plugged in, and did your user have sufficient permissions to access it as a HID device? I can clean up that init code so that it errors out with a clearer message if the device isn't fount.

**Comment by quite** [comment]
@cibomahto i did it, and on this branch! so i'll just merge it

**Comment by cibomahto** [comment]
Excellent!

**Pull request merged**
