### PR TITLE
Support raw bit file (ASCII) format

### PR DESCRIPTION
**Pull request by airskywater**
convert binary bitstream file into rbt(raw bit file (ASCII)) format to support other types of programmers.

### CODE REVIEW

**Comment by secworks** [comment]
Cool! We we look at the patch and test it.

**Comment by airskywater** [comment]
> 

LPC11U35FHI33, please  refer to https://www.eetree.cn/project/detail/131 for more details.

**Comment by airskywater** [comment]
> 

I test the python code on binary bitstream file generated by Lattice Radiant Software.
The python hardcode offset code need to be erased for binary bitstream file generated by icestorm/yosys/nextpnr software.

**Comment by airskywater** [comment]
> Cool! We we look at the patch and test it. What programmers would you use the raw bit format with?

The board is integrated with the STEPLINK function based on DAPLink download function (LPC11U35FHI33 is used for the job) . The serial Flash of FPGA can be configured directly through the USB port, and UART communication can be supported through the same USB port;

**Comment by airskywater** [comment]
> Cool! We we look at the patch and test it. What programmers would you use the raw bit format with?

LPC11U35FHI33, please refer to https://www.eetree.cn/project/detail/131 for more details.

**Comment by airskywater** [comment]
> @airskywater your python code starts by digging for date strings at certain offsets in the gateware binary. But there are only zeroes in the binary there (at least given our toolchain).

@quite 
I test the python code on binary bitstream file generated by Lattice Radiant Software.
The python hardcode offset code need to be erased for binary bitstream file generated by icestorm/yosys/nextpnr software.

**Pull request closed without merging**
