### PR TITLE
Changing names for ram address and data randomization (retry)

### PR DESCRIPTION
**Pull request by secworks**
This PR fixes issue #219 - again.
This PR does change the digests, but it is expected according to Yosys.

### CODE REVIEW

**Comment by mchack-work** [comment]
Do we use this or the other branch for going forward?

**Comment by dehanj** [comment]
> Do we use this or the other branch for going forward?

Both PRs have the same digests, so that is good.

This one have updates to the fw and `tk1_mem.h` as well, which the other does not have.
So my suggestion is to use this one.

We might want to squash a bit, i think it is enough with 2 commits. One for the FPGA, and one for FW.

**Comment by secworks** [comment]
Checked a final time. No warnings or errors. Name changes match through code, README.
The difference in resource allocation is six LCs (lower) compared tom main. This is less than a 32-bit register or XOR, shift operations on 16 or 32 bit data. I think we are ready to merge.

**Review by dehanj — APPROVED** [review]
Rebased on main, squashed. 
New digests for firmware and fpga.

**Pull request merged**
