### PR TITLE
Use firmware-only RAM for CDI computation

### PR DESCRIPTION
**Pull request by mchack-work**
To protect the UDS a bit more instead of having it in regular RAM we use the new firmware-only RAM in the CDI computation, both in the buffer passed to `blake2s()` containing UDS, app digest, and USS and the blake2s_ctx.

### CODE REVIEW

**Review by secworks — APPROVED** [review]
I've read through the changes. They look like what I expected, adding a context pointer. I see no evil. Good that the content is being wiped as soon as the CDI has been calculated.

**Comment by mchack-work** [comment]
I would like to have `fw_ram` support in qemu before merge.

**Comment by secworks** [comment]
Ready to merge now?

**Comment by mchack-work** [comment]
Merged.

**Pull request closed without merging**
