### PR TITLE
FPGA: Add system reset API

### PR DESCRIPTION
**Pull request by secworks**
Add API address to trigger system reset.
      When written to will send system_reset signal
      to the reset generator, which then perform a complete
      reset cycle of the FPGA system.

### CODE REVIEW

**Comment by secworks** [comment]
Note that this implementation does not look at the mode. This means that both a device app and FW could trigger reset. Not sure if that is something want. It made the implementation less complex.

Also, this function dropped the clock frequency somewhat. We could try an add a register to cut combinational logic.

**Comment by dehanj** [comment]
Are we missing a define in `tk1_mem.h`? 

Should it be defined like this in `tk1_mem.h`?
#define TK1_MMIO_TK1_SYSTEM_RESET 0xff0001C0

**Comment by dehanj** [comment]
Did a quick test and from what I can see it works as how I expected it to.

**Comment by mchack-work** [comment]
I'd like to see an update to `hw/application_fpga/core/tk1/README.md` describing the API to do a system reset, hopefully also describing exactly what is being reset.

**Comment by secworks** [comment]
Added description of system reset API in README. Including what is reset and what happens after a reset has been triggered.

**Review by dehanj — APPROVED** [review]

**Comment by dehanj** [comment]
Rebased, squashed, verified.

**Pull request merged**
