### PR TITLE
Sleep for a random number of cycles before reading out UDS to FW RAM 

### PR DESCRIPTION
**Pull request by quite**
Signed-off-by: Daniel Lublin <daniel@lublin.se>

### CODE REVIEW

**Comment by quite** [comment]
Please have a look @mchack-work  @secworks

**Comment by secworks** [comment]
Has anybody tried the change on a real system. I'm wondering how much the delay will be felt by the user. Esp for small applications. Would. 0.5 seconds be better?

**Comment by quite** [comment]
@secworks I already changed this to sleep for at most 64k cycles. It should be enough our purposes. And what's that, 0.0036 seconds? Can't be felt :)

**Comment by mchack-work** [comment]
Merged.

**Pull request closed without merging**
